"""02_url_access

Revision ID: 2e5c0d06477b
Revises: e2a9fa9f6cb8
Create Date: 2025-02-02 21:05:11.340614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e5c0d06477b'
down_revision: Union[str, None] = 'e2a9fa9f6cb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('client_info', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_access_id'), 'url_access', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_access_id'), table_name='url_access')
    op.drop_table('url_access')
    # ### end Alembic commands ###
